##
##	[Makefile]
##	Created by Micael Levi on 09/20/2016
##	Copyright (c) 2016 mllc@icomp.ufam.edu.br; All rights reserved.
##

#
# (em relacao ao arquivo files-newton.mk)
# MAIN		= nome do programa executavel
# SRCS		= nome dos arquivos de codigo-fonte com extensao .c
#
# (em relacao ao arquivo Makefile.global)
# CC			= comando para compilar
# CFLAGS	= flags para exibir as instrucoes
# OBJS		= nome dos objetos que serao gerados (extensao .o)
# $ make AUTO=1	[para nao exibir as instrucoes]
# $ make MOSTRAR=1 [para exibir o polinomio interpolador]
# $ make PRECISAO=p [para alterar a precisao padrão (de 3 casas para 'p' casas apos a virgula)]
#


-include files-newton.mk
-include ../Makefile.global
